version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"  # Frontend on port 3000
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "7200:7200"  # Backend now mapped to port 7200
    networks:
      - my-network
    environment:
      - NODE_ENV=production

networks:
  my-network:
    driver: bridge
